### ISSUE TITLE
Gate-save as brat

### ISSUE THREAD

**Issue by FatemehG** [GateNLP/gateplugin-Format_Brat#4]
Hi,
I'm using Gate to annotate some documents and wanted to save it in Brat format. I right click on document and click on save as brat stanadoff annotation, which it opens a window that I need to enter the output file name and  configURL, I used the config file that you have it here in your example but the output file is empty, I greatly appreciate your help if you let me know how I can fix this problem
Thanks

**Comment by greenwoodma** [comment]
I'm guessing the problem is that the annotations you are producing are not described by the config file you are using and so there is nothing to output, hence the empty file. The config file in the test folder is specific to the test documents, you'll need to produce your own brat annotation config file that describes your annotations before you try exporting as brat from within GATE.

**Comment by FatemehG** [comment]
@greenwoodma: Thanks Mark, for your prompt response that solved the problem!
